import { Inter, Poppins, Parisienne } from "next/font/google";
import "./globals.css";
import Nave from "./components/Nave";
import Footer from "./components/Footer";

export const poppins = Poppins({ subsets: ["latin"], weight: "300" });
export const inter = Inter({ subsets: ["latin"] });
export const parisienne = Parisienne({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nave poppinsClassname={poppins.className} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
